"""Seed, verify and report the four demo projects (local database only).

HOW IT STAYS HONEST
* The only privileged step is `bootstrap_users`: it creates the fictional sign-in identities and the CREATE_PROJECT platform grant in the LOCAL
  auth shim (app.system on, one transaction). Everything else runs as the real actor through the real services: project creation (PM with the
  grant), membership (PM), schedule import -> build -> activate (PM), claims / corrections / withdrawals / clarification answers (Site Engineers),
  decisions (Supervisors), issues (Site Engineers and Supervisors). No ledger row is ever inserted directly.
* Refuses a non-empty database unless it is exactly the seeded state (then it only verifies). `reset_local` empties a local setuai_v2_* database
  first; it refuses anything else. Never targets hosted Supabase, never touches another database.
* Deterministic: fixed project / user ids and codes, fixed anchor date, no clock, no randomness. Internal row ids of imported and executed rows
  are generated by the database, so reproducibility is defined over external identifiers: `digest()` hashes the business content keyed by
  activity / resource ids, and two seeded databases have the same digest."""
from __future__ import annotations

import hashlib
import json
import os
import shutil
from datetime import date, timedelta
from decimal import Decimal
from types import SimpleNamespace
from typing import Any, Callable, Dict, List, Optional

import psycopg
import psycopg.rows

from db import target_guard as tg

from ..auth import CurrentUser
from ..db import close_pool, database_url, get_pool, tx
from ..domain import claims, decisions, issues as dissues, rollups
from ..domain.common import ProjectActor, resolve_actor
from ..errors import ApiError
from ..services import documents as docs, projects as sprojects, schedules as sschedules
from . import history_plan as hp
from .projects_spec import PEOPLE, ProjectSpec, all_projects, email, project_uuid, user_id
from .schedule_gen import to_csv

ANCHOR = date(2026, 9, 30)               # "today" inside the seeded story; every business date is on or before this
SEED_VERSION = 1
EXPECTED_DIGEST: Optional[str] = "eee70fc3097ca58993b74f723674f04538ed0b930f140936822b341f9143ed80"   # frozen content digest; verify() compares against it
KEEP = {"disciplines", "discipline_aliases", "units_of_measure", "issue_categories", "schema_migrations", "_setuai_env"}
PENDING = ("REPORTED", "EXTRACTED", "MATCHED", "VALIDATED", "DISPUTED")


class SeedError(RuntimeError):
    pass


def _log(msg: str) -> None:
    print(msg, flush=True)


# ------------------------------------------------------------------------------------------------ target safety
def local_target() -> tg.Target:
    try:
        url = database_url()                                 # refuses anything the v2 guard refuses
        t = tg.check_target(url)
    except (RuntimeError, tg.GuardError) as e:
        raise SeedError(str(e)) from e
    if t.kind != "local" or not t.dbname.startswith(tg.DB_PREFIX):
        raise SeedError("the demo seed only runs against a LOCAL setuai_v2_* database")
    return t


def _conn(system: bool = False) -> psycopg.Connection:
    local_target()
    c = psycopg.connect(database_url(), autocommit=True, row_factory=psycopg.rows.dict_row)
    if system:
        c.execute("select set_config('app.system','on',false)")
    return c


def is_empty(c: psycopg.Connection) -> bool:
    return all(c.execute(q).fetchone()["n"] == 0 for q in ("select count(*) n from projects", "select count(*) n from profiles", "select count(*) n from auth.users"))


def reset_local() -> None:
    """EXPLICIT local reset: removes every non-reference row of this local database and the seed's evidence files. Refuses anything that is not local."""
    t = local_target()
    with _conn() as c:
        marker = tg.read_marker(c)
        if marker.get("env") != "integration":
            raise SeedError("refusing to reset: the database marker does not say env=integration")
        names = [r["tablename"] for r in c.execute("select tablename from pg_tables where schemaname = 'public'").fetchall() if r["tablename"] not in KEEP]
        c.execute("truncate " + ", ".join(f"public.{n}" for n in names) + ", auth.users restart identity cascade")
    from .. import storage
    root = getattr(storage.get_store(), "_root", None)
    if root is not None:
        for s in all_projects():
            shutil.rmtree(root / str(s.project_id), ignore_errors=True)
    _log(f"reset: emptied local database {t.dbname}")


# ------------------------------------------------------------------------------------------------ bootstrap (the one privileged step)
def bootstrap_users() -> Dict[str, CurrentUser]:
    users: Dict[str, CurrentUser] = {}
    with _conn(system=True) as c:
        with c.transaction():
            for handle, (name, grants) in PEOPLE.items():
                uid = user_id(handle)
                c.execute("insert into auth.users (id, email, raw_user_meta_data) values (%s,%s,%s::jsonb)", (uid, email(handle), json.dumps({"full_name": name})))
                for g in grants:
                    c.execute("insert into platform_grants (user_id, capability) values (%s,%s)", (uid, g))
                users[handle] = CurrentUser(id=uid, email=email(handle), full_name=name, capabilities=set(grants))
    return users


# ------------------------------------------------------------------------------------------------ one project
class Ctx:
    def __init__(self, spec: ProjectSpec, users: Dict[str, CurrentUser]):
        self.spec, self.users = spec, users
        self.pid = spec.project_id
        self.uid: Dict[str, Any] = {}
        self.asg: Dict[str, Dict[str, dict]] = {}        # act ext id -> resource code -> {assignment_uid, unit label, baseline}
        self.actors: Dict[str, ProjectActor] = {}
        self.plan: Optional[hp.Plan] = None
        self.stage_uid: Dict[str, Any] = {}

    def actor(self, handle: str) -> ProjectActor:
        if handle not in self.actors:
            self.actors[handle] = resolve_actor(user_id(handle), self.pid)
        return self.actors[handle]

    @property
    def sup(self) -> ProjectActor:
        return self.actor(self.spec.supervisors[0])


def create_baseline(ctx: Ctx) -> None:
    s = ctx.spec
    pm = ctx.users[s.pm]
    p = sprojects.create_project(pm, {"project_id": s.project_id, "project_code": s.code, "project_name": s.name, "description": s.description, "client_name": s.client,
                                      "project_type": s.ptype, "location": s.location, "latitude": s.lat, "longitude": s.lon, "planned_start": s.start, "planned_finish": s.finish,
                                      "lifecycle_status": s.lifecycle})
    if p["project_id"] != s.project_id:
        raise SeedError("project id mismatch")
    for h in s.supervisors:
        sprojects.add_existing_member(pm, s.project_id, email(h), "SUPERVISOR")
    for h in s.engineers:
        sprojects.add_existing_member(pm, s.project_id, email(h), "SITE_ENGINEER")
    acts_csv, res_csv = to_csv(s.root, s.acts)
    params = {"project_name": s.name, "baseline_name": f"{s.code} baseline", "data_date": s.data_date.isoformat(), "planned_start": s.start.isoformat(), "planned_finish": s.finish.isoformat()}
    imp = sschedules.stage_import(pm, s.project_id, f"{s.code.lower()}_baseline.csv", acts_csv, res_csv, params)
    built = sschedules.build_import(pm, s.project_id, imp["import_id"])
    sschedules.activate_version(pm, s.project_id, built["version_id"])
    with tx() as c:
        ver = c.execute("select version_id from schedule_versions where project_id = %s and status = 'ACTIVE'", (s.project_id,)).fetchone()["version_id"]
        for r in c.execute("select external_activity_id, activity_uid from baseline_activities where version_id = %s", (ver,)).fetchall():
            ctx.uid[r["external_activity_id"]] = r["activity_uid"]
        for r in c.execute("select ba.external_activity_id e, pr.resource_code rc, br.assignment_uid a, br.unit_of_measure u, br.baseline_qty q from baseline_resources br "
                           "join baseline_activities ba on ba.activity_row_id = br.activity_row_id join project_resources pr on pr.resource_id = br.resource_id and pr.project_id = br.project_id "
                           "where br.version_id = %s and br.measures_progress", (ver,)).fetchall():
            ctx.asg.setdefault(r["e"], {})[r["rc"]] = {"assignment_uid": r["a"], "unit": r["u"], "baseline": r["q"]}
        for r in c.execute("select wbs_name, wbs_uid from schedule_wbs where version_id = %s and node_type = 'STAGE'", (ver,)).fetchall():
            ctx.stage_uid[r["wbs_name"]] = r["wbs_uid"]
    _log(f"  {s.code}: baseline v1 active, {len(s.acts)} activities")


def _unit_label(spec: ProjectSpec, act_id: str, code: str) -> str:
    a = next(x for x in spec.acts if x.id == act_id)
    return next(r[4] for r in a.res if r[0] == code)


def _fmt(v: float) -> str:
    return f"{v:,.0f}" if float(v).is_integer() else f"{v:,.2f}"


def _text(spec: ProjectSpec, act: Any, st: hp.Step, tag: str = "") -> str:
    where = f" at {act.location}" if act.location else ""
    if st.mode == "QTY":
        parts = "; ".join(f"{_fmt(q)} {_unit_label(spec, act.id, c)} of {next(r[1] for r in act.res if r[0] == c).split(': ')[-1]}" for c, q in st.qty.items())
        body = f"{act.name}{where}: cumulative to date {parts}."
    elif st.mode == "PCT":
        body = f"{act.name}{where}: about {st.pct:.0f}% complete on the site walk-down."
    else:
        body = f"{act.name}: achieved and signed off in the site log."
    return (body + (f" {tag}" if tag else "") + f" Report of {st.on:%d %b %Y}.")[:600]


def _evidence(ctx: Ctx, handle: str, what: str, on: date) -> Any:
    """a small deterministic report document uploaded as the engineer"""
    u = ctx.users[handle]
    body = f"Site daily report - {ctx.spec.name}\nDate: {on.isoformat()}\nPrepared by: {u.full_name}\n\n{what}\n".encode()
    r = docs.upload_document(u, ctx.pid, "SITE_ENGINEER", "EVIDENCE", f"site-report-{on.isoformat()}-{hashlib.sha256(body).hexdigest()[:8]}.txt", body)
    return r["document_id"]


def run_steps(ctx: Ctx) -> None:
    spec, plan = ctx.spec, ctx.plan
    acts = {a.id: a for a in spec.acts}
    n_claims = 0
    for st in plan.steps:
        a = acts[st.act_id]
        se, sup = ctx.actor(st.engineer), ctx.sup
        uid = ctx.uid[st.act_id]
        asg = ctx.asg.get(st.act_id, {})
        quantities = [{"qty": Decimal(str(q)), "uom": _unit_label(spec, a.id, c), "basis": "CUMULATIVE", "resource_hint": c} for c, q in st.qty.items()]
        evidence = []
        if st.disposition in ("PENDING", "HOLD_OPEN", "HOLD_ANSWERED", "REJECT_CORRECT_PENDING") and spec.lifecycle == "ONGOING":
            evidence = [_evidence(ctx, st.engineer, f"Activity {a.id} - {a.name}\nWork recorded against the measurement book; quantities as per the attached summary line.", st.on)]
        sub = lambda qty, on, text, resub=None, ev=evidence: claims.submit_claim(
            se, event_date=on, raw_text=text, activity_uid=uid, quantities=qty, claimed_pct=Decimal(str(st.pct)) if st.mode == "PCT" else None,
            claimed_start=st.start, claimed_finish=st.finish, evidence_document_ids=ev, resubmits_event_id=resub)
        c = sub(quantities, st.on, _text(spec, a, st)); n_claims += 1
        cid = c["claim_id"]
        ack = {"overrun_ack_note": f"Quantity exceeds the baseline by {int(round((st.overrun - 1) * 100))}%: additional work instructed under variation order; verified against the measurement book."} if st.overrun > 1.10 else {}
        d = st.disposition
        if d == "PENDING":
            continue
        if d in ("APPROVE", "REJECT_CORRECT", "REJECT_ONLY", "REJECT_CORRECT_PENDING", "APPROVE_PCT", "EDIT", "HOLD_LOOP", "HOLD_OPEN", "HOLD_ANSWERED"):
            if d == "APPROVE":
                decisions.decide(sup, cid, action="APPROVE", **ack)
            elif d == "APPROVE_PCT":
                decisions.decide(sup, cid, action="APPROVE", method="APPLY_PCT_TO_ASSIGNMENTS")
            elif d == "EDIT":
                aq = {str(asg[code]["assignment_uid"]): {"cumulative": Decimal(str(round(q * 0.97, 2)))} for code, q in st.qty.items()}
                decisions.decide(sup, cid, action="EDIT", justification="Measurement book reconciled; approved at 97% of the reported cumulative.", approved_quantities=aq)
            elif d.startswith("REJECT"):
                decisions.decide(sup, cid, action="REJECT", justification="Reported figures do not match the measurement book for this period; re-measure and resubmit.")
                if d != "REJECT_ONLY":
                    q2 = [{**q, "qty": (q["qty"] * Decimal("0.95")).quantize(Decimal("0.01"))} for q in quantities]
                    fix = sub(q2, st.on, _text(spec, a, st, "Corrected after re-measurement."), resub=cid, ev=[]); n_claims += 1
                    if d == "REJECT_CORRECT":
                        decisions.decide(sup, fix["claim_id"], action="APPROVE")
            else:                                                    # HOLD_*
                decisions.decide(sup, cid, action="HOLD", justification="Clarification requested", clarification_question="Which section and measurement-book page does this figure come from?")
                if d in ("HOLD_LOOP", "HOLD_ANSWERED"):
                    claims.answer_clarification(se, cid, "Section as per the daily plan; measurement book page 41, countersigned by the contractor's engineer.")
                    if d == "HOLD_LOOP":
                        decisions.decide(sup, cid, action="APPROVE")
    for w in plan.withdrawals:
        a = acts[w.act_id]
        se = ctx.actor(w.engineer)
        c = claims.submit_claim(se, event_date=w.on, raw_text=f"{a.name}: progress about 5% to date, start of work.", activity_uid=ctx.uid[w.act_id], claimed_pct=Decimal(5))
        claims.withdraw_claim(se, c["claim_id"], w.reason)
        n_claims += 1
    _log(f"  {spec.code}: {n_claims} claims filed and processed")


def run_issues(ctx: Ctx) -> None:
    spec, plan = ctx.spec, ctx.plan
    rc_ids: Dict[str, Any] = {}
    for rc in plan.root_causes:
        rc_ids[rc.key] = dissues.create_root_cause(ctx.sup, title=rc.title, category_code=rc.category, summary=rc.summary)["root_cause_id"]
    for i in plan.issues:
        reporter = ctx.sup if i.reported_by == "SUP" else ctx.actor(i.reported_by)
        ev = []
        if i.evidence:
            u = ctx.users[i.reported_by if i.reported_by != "SUP" else spec.supervisors[0]]
            body = f"Issue note - {spec.name}\n{i.title}\nDate: {i.reported_on.isoformat()}\n{i.description}\n".encode()
            kind = "ISSUE_REPORT"
            role = "SUPERVISOR" if i.reported_by == "SUP" else "SITE_ENGINEER"
            ev = [docs.upload_document(u, ctx.pid, role, kind, f"issue-{i.key}.txt", body)["document_id"]]
        r = dissues.report_issue(reporter, title=i.title, category_code=i.category, activity_uid=ctx.uid.get(i.act_id) if i.act_id else None,
                                 stage_wbs_uid=ctx.stage_uid[i.stage] if i.stage else None, description=i.description, severity=i.severity, blocks_work=i.blocks,
                                 reported_date=i.reported_on, delay_started_on=i.reported_on, impact_days_estimated=Decimal(str(i.estimate_days)), evidence_document_ids=ev)
        iid = r["issue_id"]
        if i.root_cause:
            dissues.assign_root_cause(ctx.sup, iid, rc_ids[i.root_cause])
        if i.resolved_days is not None:
            dissues.resolve_issue(ctx.sup, iid, i.notes or "Resolved on site.", delay_ended_on=i.reported_on + timedelta(days=i.resolved_days), impact_days_actual=Decimal(str(i.actual_days or i.resolved_days)))
            if i.memory:
                dissues.promote_to_memory(ctx.sup, iid, lessons_learned=i.memory, corrective_action=i.notes or None, outcome="Applied on later work packages.", visibility="ORGANISATION")
    _log(f"  {spec.code}: {len(plan.issues)} issues, {len(plan.root_causes)} root causes")


# ------------------------------------------------------------------------------------------------ seed
def seed(*, reset: bool = False, log: Callable[[str], None] = _log) -> Dict[str, Any]:
    local_target()
    if reset:
        reset_local()
    with _conn() as c:
        empty = is_empty(c)
    if not empty:
        rep = verify(strict=False)
        if rep["ok"]:
            log("already seeded: the database holds exactly the demo state; nothing was changed")
            return rep
        raise SeedError("the database is not empty and is not the seeded demo state; refusing to seed (use --reset-local on a LOCAL database to start over)")
    get_pool()
    users = bootstrap_users()
    log("bootstrap: 15 fictional users and 3 CREATE_PROJECT grants (local auth shim)")
    for spec in all_projects():
        ctx = Ctx(spec, users)
        ctx.plan = hp.build_plan(spec, ANCHOR)
        create_baseline(ctx)
        if spec.lifecycle != "UPCOMING":
            run_steps(ctx)
            run_issues(ctx)
        else:
            log(f"  {spec.code}: upcoming - no execution history by design")
    rep = verify(strict=True)
    close_pool()
    return rep


# ------------------------------------------------------------------------------------------------ measurement
def p3(x) -> str:
    return str(Decimal(str(x)).quantize(Decimal("0.001")))


def _project_metrics(c, spec: ProjectSpec) -> Dict[str, Any]:
    pid = spec.project_id
    q = lambda sql, *a: c.execute(sql, a).fetchall()
    one = lambda sql, *a: c.execute(sql, a).fetchone()
    ver = one("select version_id, version_no from schedule_versions where project_id = %s and status = 'ACTIVE'", pid)
    m: Dict[str, Any] = {"code": spec.code, "lifecycle": spec.lifecycle}
    if ver is None:
        raise SeedError(f"{spec.code}: no active schedule version")
    vid = ver["version_id"]
    m["versions"] = {r["status"]: r["n"] for r in q("select status, count(*) n from schedule_versions where project_id = %s group by status", pid)}
    acts = q("select * from activity_progress_as_of(%s, %s) order by external_activity_id", vid, ANCHOR)
    m["activities"] = len(acts)
    m["activity_states"] = {s: sum(1 for a in acts if a["execution_state"] == s) for s in ("NOT_STARTED", "IN_PROGRESS", "COMPLETED")}
    proj = one("select * from project_progress_as_of(%s, %s)", vid, ANCHOR)
    m["physical_pct"], m["planned_pct"], m["weight_basis"] = p3(proj["physical_pct"]), p3(proj["planned_pct"]), proj["weight_basis"]
    m["min_activity_pct"], m["max_activity_pct"] = p3(min(a["physical_pct"] for a in acts)), p3(max(a["physical_pct"] for a in acts))
    wbs = q("select * from wbs_progress_as_of(%s, %s)", vid, ANCHOR)
    m["wbs_pct_range"] = [p3(min(w["physical_pct"] for w in wbs)), p3(max(w["physical_pct"] for w in wbs))]
    disc = q("select * from discipline_progress_as_of(%s, %s)", vid, ANCHOR)
    m["discipline_pct_range"] = [p3(min(d["physical_pct"] for d in disc)), p3(max(d["physical_pct"] for d in disc))]
    end = ANCHOR if spec.start <= ANCHOR else spec.finish                      # an upcoming project's timeline is its own (future) planned window
    tl = q("select * from progress_timeline(%s, (select min(baseline_start) from baseline_activities where version_id = %s), %s, 30)", vid, vid, end)
    m["timeline_last_pct"] = p3(tl[-1]["physical_pct"]) if tl else None
    m["timeline_max_pct"] = p3(max(t["physical_pct"] for t in tl)) if tl else None
    m["claims"] = {r["status"]: r["n"] for r in q("select status, count(*) n from execution_events where project_id = %s group by status", pid)}
    m["claims_pending"] = sum(m["claims"].get(s, 0) for s in PENDING)
    m["claims_resubmitted"] = one("select count(*) n from execution_events where project_id = %s and resubmits_event_id is not null", pid)["n"]
    m["rejected_without_correction"] = one("select count(*) n from execution_events e where e.project_id = %s and e.status = 'REJECTED' and not exists (select 1 from execution_events x where x.resubmits_event_id = e.event_id)", pid)["n"]
    m["clarification"] = {(r["clarification_status"] or "NONE"): r["n"] for r in q("select clarification_status, count(*) n from execution_events where project_id = %s group by clarification_status", pid)}
    m["decisions"] = {f"{r['action']}/{r['method']}": r["n"] for r in q("select action, method, count(*) n from planner_decisions where project_id = %s group by action, method", pid)}
    m["decisions_total"] = sum(m["decisions"].values())
    m["overrun_ack"] = one("select count(*) n from planner_decisions where project_id = %s and overrun_ack", pid)["n"]
    m["ledger"] = {"resource": one("select count(*) n from approved_resource_progress where project_id = %s", pid)["n"], "activity": one("select count(*) n from approved_activity_progress where project_id = %s", pid)["n"]}
    m["ledger_over_baseline"] = one("select count(*) n from approved_resource_progress where project_id = %s and over_baseline", pid)["n"]
    m["ledger_units"] = sorted(r["u"] for r in q("select distinct br.unit_of_measure u from approved_resource_progress r join baseline_resources br on br.assignment_uid = r.assignment_uid and br.version_id = %s where r.project_id = %s", vid, pid))
    m["ledger_inconsistent"] = one(
        "select count(*) n from (select r.assignment_uid, sum(r.incremental_qty) s, (array_agg(r.cumulative_qty order by r.entry_seq desc))[1] last from approved_resource_progress r "
        "where r.project_id = %s group by r.assignment_uid) t where t.s <> t.last", pid)["n"]
    m["ledger_non_monotone"] = one("select count(*) n from approved_resource_progress where project_id = %s and incremental_qty < 0", pid)["n"]
    m["issues"] = {r["status"]: r["n"] for r in q("select status, count(*) n from issues where project_id = %s group by status", pid)}
    m["issues_blocking_active"] = one("select count(*) n from issues where project_id = %s and status = 'ACTIVE' and blocks_work", pid)["n"]
    m["issues_stage_level_active"] = one("select count(*) n from issues where project_id = %s and status = 'ACTIVE' and stage_wbs_uid is not null", pid)["n"]
    m["root_causes"] = one("select count(*) n from root_causes where project_id = %s", pid)["n"]
    m["root_causes_with_2plus_issues"] = one("select count(*) n from (select root_cause_id from issues where project_id = %s and root_cause_id is not null group by root_cause_id having count(*) >= 2) t", pid)["n"]
    m["memory"] = one("select count(*) n from institutional_memory where project_id = %s", pid)["n"]
    m["documents"] = {r["kind"]: r["n"] for r in q("select kind, count(*) n from source_documents where project_id = %s group by kind", pid)}
    m["notifications"] = {r["notification_type"]: r["n"] for r in q("select notification_type, count(*) n from notifications where project_id = %s group by notification_type", pid)}
    m["audit_entries"] = one("select count(*) n from audit_logs where project_id = %s", pid)["n"]
    m["members"] = {r["role"]: r["n"] for r in q("select role, count(*) n from project_memberships where project_id = %s and status = 'ACTIVE' group by role", pid)}
    m["per_activity"] = [[a["external_activity_id"], str(a["physical_pct"]), a["execution_state"], str(a["actual_start"]) if a["actual_start"] else None, str(a["actual_finish"]) if a["actual_finish"] else None] for a in acts]
    m["per_assignment"] = [[r["e"], r["rc"], str(r["cum"])] for r in q(
        "select ba.external_activity_id e, pr.resource_code rc, (select cumulative_qty from approved_resource_progress x where x.assignment_uid = br.assignment_uid order by x.entry_seq desc limit 1) cum "
        "from baseline_resources br join baseline_activities ba on ba.activity_row_id = br.activity_row_id join project_resources pr on pr.resource_id = br.resource_id and pr.project_id = br.project_id "
        "where br.version_id = %s and br.measures_progress order by 1, 2", vid)]
    m["audit_chain"] = None
    return m


def collect() -> Dict[str, Any]:
    out: Dict[str, Any] = {"seed_version": SEED_VERSION, "anchor": ANCHOR.isoformat(), "projects": {}}
    with tx(readonly=True) as c:
        for spec in all_projects():
            if c.execute("select 1 from projects where project_id = %s", (spec.project_id,)).fetchone() is None:
                raise SeedError(f"project {spec.code} is missing")
            out["projects"][spec.code] = _project_metrics(c, spec)
        from .. import audit
        chain = audit.verify_chain(c)
        out["audit_chain"] = {"valid": chain["valid"], "entries": chain["entries"]}
        out["extra_projects"] = c.execute("select count(*) n from projects where project_id <> all(%s)", ([s.project_id for s in all_projects()],)).fetchone()["n"]
        out["users"] = c.execute("select count(*) n from profiles").fetchone()["n"]
    return out


def digest(rep: Dict[str, Any]) -> str:
    core = {"v": rep["seed_version"], "anchor": rep["anchor"], "users": rep["users"], "projects": {k: {kk: vv for kk, vv in v.items() if kk != "audit_entries"} for k, v in rep["projects"].items()}}
    return hashlib.sha256(json.dumps(core, sort_keys=True, default=str).encode()).hexdigest()


# ------------------------------------------------------------------------------------------------ invariants
def check(rep: Dict[str, Any]) -> List[str]:
    f: List[str] = []
    P = rep["projects"]
    if rep.get("extra_projects"):
        f.append("the database holds projects other than the four demo projects")
    if rep.get("users") != len(PEOPLE):
        f.append(f"the database holds {rep.get('users')} users; the demo has exactly {len(PEOPLE)}")
    if not rep["audit_chain"]["valid"]:
        f.append("the audit hash chain does not verify")
    for code, m in P.items():
        if m["ledger_inconsistent"]:
            f.append(f"{code}: {m['ledger_inconsistent']} assignment(s) whose incremental quantities do not sum to the latest cumulative")
        if m["ledger_non_monotone"]:
            f.append(f"{code}: negative incremental ledger entries")
        if m["versions"].get("ACTIVE") != 1 or sum(m["versions"].values()) != 1:
            f.append(f"{code}: expected exactly one (active) schedule version, got {m['versions']}")
    a, b, c_, d = (P.get(k) for k in ("NNB-CRUDE", "AEC-OFFSHORE", "NRL-EXPANSION", "SMP-PIPE"))
    if a:
        if (a["physical_pct"], a["min_activity_pct"], a["wbs_pct_range"], a["discipline_pct_range"], a["timeline_last_pct"]) != ("100.000", "100.000", ["100.000", "100.000"], ["100.000", "100.000"], "100.000"):
            f.append(f"A: not every rollup is 100%: {a['physical_pct']} {a['min_activity_pct']} {a['wbs_pct_range']} {a['discipline_pct_range']} {a['timeline_last_pct']}")
        if a["activity_states"]["COMPLETED"] != a["activities"]:
            f.append("A: not every activity is COMPLETED")
        if a["claims_pending"] or a["issues"].get("ACTIVE"):
            f.append("A: pending claims or active issues remain")
        if a["issues"].get("RESOLVED", 0) < 8 or a["memory"] < 2 or a["rejected_without_correction"] or a["claims_resubmitted"] < 4 or a["ledger_over_baseline"] < 1:
            f.append("A: expected resolved issues, memory entries, corrected rejections and one within-tolerance overrun")
    for code, m in (("B", b), ("C", c_)):
        if not m:
            continue
        if not (Decimal("0") < Decimal(m["physical_pct"]) < Decimal("100")) or min(m["activity_states"].values()) == 0:
            f.append(f"{code}: progress should be mixed (some completed, some in progress, some not started): {m['physical_pct']} {m['activity_states']}")
        if m["claims_pending"] < 3:
            f.append(f"{code}: expected pending claims")
        if m["issues_blocking_active"] < 2 or m["issues"].get("RESOLVED", 0) < 2:
            f.append(f"{code}: expected active blockers and resolved issues")
        if len(m["ledger_units"]) < 3:
            f.append(f"{code}: expected several measured unit kinds, got {m['ledger_units']}")
        if m["claims"].get("WITHDRAWN", 0) < 1 or m["claims"].get("REJECTED", 0) < 1 or m["claims_resubmitted"] < 1 or m["ledger_over_baseline"] < 1:
            f.append(f"{code}: expected a withdrawal, a rejection with a correction and an over-baseline entry")
    if b and (b["issues_stage_level_active"] < 1 or b["clarification"].get("ASKED", 0) < 1):
        f.append("B: expected a stage-level blocker and an open clarification")
    if c_:
        if c_["root_causes_with_2plus_issues"] < 2 or c_["memory"] < 1:
            f.append("C: expected root causes grouping several issues and a memory entry")
        if c_["clarification"].get("ANSWERED", 0) < 2 or c_["clarification"].get("ASKED", 0) < 1 or c_["overrun_ack"] < 1 or c_["decisions"].get("APPROVE/APPLY_PCT_TO_ASSIGNMENTS", 0) < 3:
            f.append("C: expected clarification workflows, an acknowledged over-tolerance approval and three explicit percent applications")
    if d:
        zero = {"claims": d["claims"], "decisions": d["decisions"], "ledger_resource": d["ledger"]["resource"], "ledger_activity": d["ledger"]["activity"], "issues": d["issues"],
                "notifications": d["notifications"], "root_causes": d["root_causes"], "memory": d["memory"]}
        if any(v for v in zero.values()):
            f.append(f"D: execution history must be empty: {zero}")
        if d["physical_pct"] != "0.000" or d["max_activity_pct"] != "0.000" or d["wbs_pct_range"] != ["0.000", "0.000"] or d["discipline_pct_range"] != ["0.000", "0.000"] or d["timeline_max_pct"] != "0.000":
            f.append("D: every actual-progress rollup must be exactly zero")
        if d["activity_states"]["NOT_STARTED"] != d["activities"]:
            f.append("D: every activity must be NOT_STARTED")
        if set(d["documents"]) - {"SCHEDULE_FILE"}:
            f.append("D: only the schedule file may exist as a document")
        if d["audit_entries"] == 0:
            f.append("D: expected administrative audit entries (project, members, import)")
    return f


def verify(strict: bool = True) -> Dict[str, Any]:
    """read-only. Raises SeedError with the failures when strict; otherwise returns the report with ok=False."""
    local_target()                                           # a refused target is always an error, strict or not
    try:
        rep = collect()
    except (SeedError, ApiError, psycopg.Error) as e:
        if strict:
            raise SeedError(f"verification could not run: {e}") from e
        return {"ok": False, "problems": [str(e)]}
    problems = check(rep)
    rep["digest"] = digest(rep)
    if EXPECTED_DIGEST is not None and rep["digest"] != EXPECTED_DIGEST:
        problems.append(f"content digest {rep['digest'][:16]}... differs from the expected {EXPECTED_DIGEST[:16]}... (the generator changed, or the database was edited)")
    rep["problems"], rep["ok"] = problems, not problems
    if problems and strict:
        raise SeedError("verification failed:\n  - " + "\n  - ".join(problems))
    return rep


# ------------------------------------------------------------------------------------------------ report
def format_report(rep: Dict[str, Any]) -> str:
    lines = [f"Seed report (anchor {rep['anchor']}, seed v{rep['seed_version']}, digest {rep.get('digest', '?')[:16]})", ""]
    head = f"{'':28}{'A NNB-CRUDE':>14}{'B AEC-OFFSHORE':>16}{'C NRL-EXPANSION':>17}{'D SMP-PIPE':>13}"
    lines.append(head)
    P = [rep["projects"][k] for k in ("NNB-CRUDE", "AEC-OFFSHORE", "NRL-EXPANSION", "SMP-PIPE")]
    row = lambda label, fn: lines.append(f"{label:28}" + "".join(f"{str(fn(m)):>{w}}" for m, w in zip(P, (14, 16, 17, 13))))
    row("lifecycle", lambda m: m["lifecycle"]); row("activities", lambda m: m["activities"])
    row("  completed", lambda m: m["activity_states"]["COMPLETED"]); row("  in progress", lambda m: m["activity_states"]["IN_PROGRESS"]); row("  not started", lambda m: m["activity_states"]["NOT_STARTED"])
    row("actual progress %", lambda m: m["physical_pct"]); row("planned % (approx.)", lambda m: m["planned_pct"]); row("weight basis", lambda m: m["weight_basis"])
    row("schedule versions", lambda m: sum(m["versions"].values()))
    row("claims (all)", lambda m: sum(m["claims"].values()))
    for s in ("APPROVED", "REJECTED", "WITHDRAWN", "DISPUTED", "MATCHED"):
        row(f"  {s.lower()}", lambda m, s=s: m["claims"].get(s, 0))
    row("  pending (open)", lambda m: m["claims_pending"]); row("  corrections (linked)", lambda m: m["claims_resubmitted"])
    row("decisions", lambda m: m["decisions_total"]); row("  over-baseline acknowledged", lambda m: m["overrun_ack"])
    row("ledger: resource entries", lambda m: m["ledger"]["resource"]); row("ledger: activity entries", lambda m: m["ledger"]["activity"]); row("  entries over baseline", lambda m: m["ledger_over_baseline"])
    row("issues: resolved", lambda m: m["issues"].get("RESOLVED", 0)); row("issues: active", lambda m: m["issues"].get("ACTIVE", 0)); row("  active blockers", lambda m: m["issues_blocking_active"])
    row("root causes", lambda m: m["root_causes"]); row("memory entries", lambda m: m["memory"])
    row("documents (non-schedule)", lambda m: sum(v for k, v in m["documents"].items() if k != "SCHEDULE_FILE")); row("notifications", lambda m: sum(m["notifications"].values())); row("audit entries", lambda m: m["audit_entries"])
    lines += ["", f"audit chain: {'valid' if rep['audit_chain']['valid'] else 'BROKEN'} ({rep['audit_chain']['entries']} entries); users: {rep['users']}",
              "status: " + ("OK - all invariants hold" if rep.get("ok") else "PROBLEMS: " + "; ".join(rep.get("problems", [])))]
    return "\n".join(lines)
