"""Project permissions by project role. The database enforces the same separation independently (migrations 0001-0009)."""
from __future__ import annotations

from typing import Dict, Set

PM, SUP, SE = "PROJECT_MANAGER", "SUPERVISOR", "SITE_ENGINEER"

VIEW_PROJECT, VIEW_SCHEDULE = "VIEW_PROJECT", "VIEW_SCHEDULE"
MANAGE_PROJECT, MANAGE_SETTINGS = "MANAGE_PROJECT", "MANAGE_SETTINGS"
MANAGE_MEMBERS, VIEW_MEMBERS = "MANAGE_MEMBERS", "VIEW_MEMBERS"
MANAGE_SCHEDULE, ACTIVATE_SCHEDULE = "MANAGE_SCHEDULE", "ACTIVATE_SCHEDULE"
UPLOAD_REPORT = "UPLOAD_REPORT"

ROLE_PERMISSIONS: Dict[str, Set[str]] = {
    PM: {VIEW_PROJECT, VIEW_SCHEDULE, MANAGE_PROJECT, MANAGE_SETTINGS, MANAGE_MEMBERS, VIEW_MEMBERS, MANAGE_SCHEDULE, ACTIVATE_SCHEDULE},
    SUP: {VIEW_PROJECT, VIEW_SCHEDULE, VIEW_MEMBERS},
    SE: {VIEW_PROJECT, VIEW_SCHEDULE, UPLOAD_REPORT},
}
