"""Project permissions by project role. The database enforces the same separation independently (migrations 0001-0014); the domain
services re-check the role inside each transaction. A permission here is only the first, cheap gate."""
from __future__ import annotations

from typing import Dict, Set

PM, SUP, SE = "PROJECT_MANAGER", "SUPERVISOR", "SITE_ENGINEER"

VIEW_PROJECT, VIEW_SCHEDULE = "VIEW_PROJECT", "VIEW_SCHEDULE"
MANAGE_PROJECT, MANAGE_SETTINGS = "MANAGE_PROJECT", "MANAGE_SETTINGS"
MANAGE_MEMBERS, VIEW_MEMBERS = "MANAGE_MEMBERS", "VIEW_MEMBERS"
MANAGE_SCHEDULE, ACTIVATE_SCHEDULE = "MANAGE_SCHEDULE", "ACTIVATE_SCHEDULE"
UPLOAD_REPORT = "UPLOAD_REPORT"                  # report / photograph / evidence files (Site Engineer: all kinds)
UPLOAD_EVIDENCE = "UPLOAD_EVIDENCE"              # issue evidence (Supervisor and Site Engineer)
VIEW_DOCUMENTS = "VIEW_DOCUMENTS"                # role-filtered inside the service
SUBMIT_CLAIM, VIEW_OWN_CLAIMS = "SUBMIT_CLAIM", "VIEW_OWN_CLAIMS"
REVIEW_CLAIMS = "REVIEW_CLAIMS"                  # queue, claim detail, decisions
VIEW_CLAIM_COUNTS = "VIEW_CLAIM_COUNTS"          # aggregate counts only
REPORT_ISSUE, VIEW_ISSUES, RESOLVE_ISSUE = "REPORT_ISSUE", "VIEW_ISSUES", "RESOLVE_ISSUE"
VIEW_DASHBOARD, VIEW_AUDIT = "VIEW_DASHBOARD", "VIEW_AUDIT"
VIEW_ROOT_CAUSES = "VIEW_ROOT_CAUSES"            # root causes: Supervisor and Project Manager
VIEW_QUALITY, MANAGE_QUALITY, SUBMIT_QUALITY_EVIDENCE = "VIEW_QUALITY", "MANAGE_QUALITY", "SUBMIT_QUALITY_EVIDENCE"      # quality gates: all read; Supervisor manages / decides; engineers and supervisors submit evidence

ROLE_PERMISSIONS: Dict[str, Set[str]] = {
    PM: {VIEW_PROJECT, VIEW_SCHEDULE, MANAGE_PROJECT, MANAGE_SETTINGS, MANAGE_MEMBERS, VIEW_MEMBERS, MANAGE_SCHEDULE, ACTIVATE_SCHEDULE,
         VIEW_DOCUMENTS, VIEW_CLAIM_COUNTS, VIEW_ISSUES, VIEW_DASHBOARD, VIEW_AUDIT, VIEW_ROOT_CAUSES, VIEW_QUALITY},
    SUP: {VIEW_PROJECT, VIEW_SCHEDULE, VIEW_MEMBERS, UPLOAD_EVIDENCE, VIEW_DOCUMENTS, REVIEW_CLAIMS, VIEW_CLAIM_COUNTS, REPORT_ISSUE, VIEW_ISSUES, RESOLVE_ISSUE,
          VIEW_DASHBOARD, VIEW_AUDIT, VIEW_ROOT_CAUSES, VIEW_QUALITY, MANAGE_QUALITY, SUBMIT_QUALITY_EVIDENCE},
    SE: {VIEW_PROJECT, VIEW_SCHEDULE, UPLOAD_REPORT, UPLOAD_EVIDENCE, VIEW_DOCUMENTS, SUBMIT_CLAIM, VIEW_OWN_CLAIMS, REPORT_ISSUE, VIEW_ISSUES, VIEW_DASHBOARD, VIEW_QUALITY, SUBMIT_QUALITY_EVIDENCE},
}
