#!/usr/bin/env python3
"""Generate docs/V2_API.md from the live OpenAPI schema, the verified role table (tests/v2_api/test_api_roles.py) and the error codes in the source.

    python3 scripts/gen_v2_api_doc.py            # rewrite docs/V2_API.md
    python3 scripts/gen_v2_api_doc.py --check    # exit 1 if the file is stale (also run by the test-suite)"""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tests" / "v2_api"))
sys.path.insert(0, str(ROOT / "tests" / "schedule_import"))
sys.path.insert(0, str(ROOT / "tests" / "v2_domain"))
os.environ.setdefault("SUPABASE_JWT_SECRET", "x" * 40)

DOC = ROOT / "docs" / "V2_API.md"
GROUPS = [("Project Manager", "M"), ("Supervisor", "S"), ("Site Engineer", "E")]


def render() -> str:
    from backend.v2.app import create_app
    spec = create_app().openapi()
    import test_api_roles as roles
    by = {}
    for path, item in spec["paths"].items():
        for method, op in item.items():
            by[(method.upper(), roles.canonical(path))] = (path, op)
    out = ["# SetuAI v2 API reference", "",
           "Generated by `scripts/gen_v2_api_doc.py` from the running application's OpenAPI schema and from the role table that `tests/v2_api/test_api_roles.py` verifies "
           "against real requests. Do not edit by hand; `python3 scripts/gen_v2_api_doc.py` rewrites it and a test fails if it is stale.", "",
           "All paths are under `/api/v2`. Authenticate with `Authorization: Bearer <JWT>`. Project authority comes from an ACTIVE membership of the project in the path.",
           "Errors: `{\"error\": {\"code\", \"message\", \"details\"}}`. Lists: `{\"items\", \"limit\", \"offset\", \"next_offset\"}` (limit 1-200). "
           "Create endpoints accept an `Idempotency-Key` header (claims, corrections, issues).", "",
           "Roles: **M** Project Manager · **S** Supervisor · **E** Site Engineer. The letters are who passes the permission gate; finer rules (own records only, "
           "no claim content for the PM) are enforced by the domain services and the database and described in the summary.", ""]
    out += ["## Endpoints by role", ""]
    for title, letter in GROUPS:
        out += [f"### {title}", "", "| Method | Path | Roles | What it does |", "|---|---|---|---|"]
        for (m, p), who in sorted(roles.ROUTES.items(), key=lambda kv: (kv[0][1], kv[0][0])):
            if letter in who:
                path, op = by[(m, roles.canonical(p))]
                out.append(f"| {m} | `{path.replace('/api/v2', '')}` | {who} | {op.get('summary', '')} |")
        out.append("")
    out += ["### Account-level and platform endpoints", "", "| Method | Path | Who | What it does |", "|---|---|---|---|"]
    for (m, p), kind in sorted(roles.GLOBAL.items(), key=lambda kv: (kv[0][1], kv[0][0])):
        path, op = by[(m, roles.canonical(p))]
        who = {"public": "anyone (health check)", "user": "any signed-in user", "grant": "`CREATE_PROJECT` platform grant", "admin": "`PLATFORM_ADMIN` platform grant"}[kind]
        out.append(f"| {m} | `{path.replace('/api/v2', '')}` | {who} | {op.get('summary', '')} |")
    codes = {}
    for f in sorted((ROOT / "backend" / "v2").rglob("*.py")):
        if "seed" in f.parts:
            continue
        for m in re.finditer(r'ApiError\((\d{3}), "([A-Z_]+)"', f.read_text()):
            codes.setdefault(m.group(2), set()).add(int(m.group(1)))
    out += ["", "## Error codes", "", "| Code | HTTP status |", "|---|---|"]
    out += [f"| `{c}` | {', '.join(str(s) for s in sorted(codes[c]))} |" for c in sorted(codes)]
    out += ["", f"{len(roles.ROUTES) + len(roles.GLOBAL)} operations, {len(codes)} stable error codes.", ""]
    return "\n".join(out)


def main(argv) -> int:
    text = render()
    if "--check" in argv:
        if not DOC.exists() or DOC.read_text() != text:
            print("docs/V2_API.md is stale: run python3 scripts/gen_v2_api_doc.py", file=sys.stderr)
            return 1
        return 0
    DOC.parent.mkdir(exist_ok=True)
    DOC.write_text(text)
    print(f"wrote {DOC.relative_to(ROOT)} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
